server:
  port: 8095
  error:
    whitelabel:
      enabled: true
    include-stacktrace: always

listeUtilisateur: ttttttttttt2222

spring:
  datasource:
#    url: jdbc:h2:tcp://10.0.0.248:9092/~/testdb
    url: jdbc:h2:tcp://localhost:9024/bmdb
#    url: "jdbc:h2:mem:testdb;Mode=Oracle;INIT=runscript from 'classpath:/shema.sql'"
#    url: jdbc:h2:tcp://10.0.0.192:9092/~/testdb
#    url: jdbc:h2:tcp://10.0.0.192:9092/~/h2database/testdb
#    url: jdbc:h2:tcp://192.168.2.48:9092/~/testdb
#    url: jdbc:h2:tcp://192.168.2.48:9092/~/testdb
#    url: jdbc:h2:tcp://192.168.2.48:9092/~/testdb


    username: sa
    platform: h2
    continue-on-error: true
#    initialization-mode: embedded
    initialization-mode: never

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2
  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 2GB

