create table User22
(
    id int auto_increment primary key,
    NAME VARCHAR2(15),
    SURNAME VARCHAR2(15),
    EMAIL VARCHAR2(15),
    USERNAME VARCHAR2(15),
    PASSWORD VARCHAR2(15)
);

CREATE SEQUENCE SEQ_BATCH_PER_DAY
    MINVALUE 4000
    MAXVALUE 7000
    INCREMENT BY 1
    START WITH 4000
    CYCLE;

INSERT INTO User22 (NAME, SURNAME, EMAIL, USERNAME, PASSWORD) VALUES('NAME3', 'SURNAME1', 'EMAIL3', 'USERNAME3', 'PASSWORD3');
INSERT INTO User22 (NAME, SURNAME, EMAIL, USERNAME, PASSWORD) VALUES('NAME3', 'SURNAME2', 'EMAIL3', 'USERNAME3', 'PASSWORD3');
INSERT INTO User22 (NAME, SURNAME, EMAIL, USERNAME, PASSWORD) VALUES('NAME3', 'SURNAME3', 'EMAIL3', 'USERNAME3', 'PASSWORD3');
INSERT INTO User22 (NAME, SURNAME, EMAIL, USERNAME, PASSWORD) VALUES('NAME3', 'SURNAME3', 'EMAIL3', 'USERNAME3', 'PASSWORD3');
INSERT INTO User22 (NAME, SURNAME, EMAIL, USERNAME, PASSWORD) VALUES('NAME3', 'SURNAME4', 'EMAIL3', 'USERNAME3', 'PASSWORD3');
INSERT INTO User22 (NAME, SURNAME, EMAIL, USERNAME, PASSWORD) VALUES('NAME3', 'SURNAME5', 'EMAIL3', 'USERNAME3', 'PASSWORD3');
INSERT INTO User22 (NAME, SURNAME, EMAIL, USERNAME, PASSWORD) VALUES('NAME3', 'SURNAME6', 'EMAIL3', 'USERNAME3', 'PASSWORD3');
INSERT INTO User22 (NAME, SURNAME, EMAIL, USERNAME, PASSWORD) VALUES('NAME3', 'SURNAME7', 'EMAIL3', 'USERNAME3', 'PASSWORD3');
INSERT INTO User22 (NAME, SURNAME, EMAIL, USERNAME, PASSWORD) VALUES('NAME3', 'SURNAME8', 'EMAIL3', 'USERNAME3', 'PASSWORD3');
INSERT INTO User22 (NAME, SURNAME, EMAIL, USERNAME, PASSWORD) VALUES('NAME3', 'SURNAME9', 'EMAIL3', 'USERNAME3', 'PASSWORD3');
INSERT INTO User22 (NAME, SURNAME, EMAIL, USERNAME, PASSWORD) VALUES('NAME3', 'SURNAME10', 'EMAIL3', 'USERNAME3', 'PASSWORD3');


create table test(id bigint auto_increment, name varchar(255));
insert into test(name) values('hello');
insert into test(name) values('world');
select * from test;
