package guru.springframework.basicauth.model;

import lombok.*;

import javax.persistence.*;
import java.math.BigInteger;

@Entity
@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
@Data
@Table(name = "TOUSLESFILMS")
public class TousLesFilms {

    @Id
    private BigInteger Id;

    @Column(name = "TITRE_FRANCAIS")
    private String titre_Français;
    @Column(name = "TITRE_ANGLAIS")
    private String titreAnglais;
    @Column(name = "ANNEE")
    private String annee;
    @Column(name = "POCHETTE")
    private String pochette;
    @Column(name = "Disque_Francais")
    private String disque_Francais;
    @Column(name = "Disque_Anglais")
    private String disque_Anglais;
    @Column(name = "ACT")
    private String act;
    @Column(name = "ANIM")
    private String anim;
    @Column(name = "AVEN")
    private String aven;
    @Column(name = "BIO")
    private String bio;
    @Column(name = "BONUS")
    private String bonus;
    @Column(name = "COM")
    private String com;
    @Column(name = "CRIME")
    private String crime;
    @Column(name = "DOC")
    private String doc;
    @Column(name = "DRAME")
    private String drame;
    @Column(name = "FANT")
    private String fant;
    @Column(name = "GUER")
    private String guer;
    @Column(name = "HIST")
    private String hist;
    @Column(name = "HOR")
    private String hor;
    @Column(name = "MUS")
    private String mus;
    @Column(name = "MYST")
    private String myst;
    @Column(name = "ROM")
    private String rom;
    @Column(name = "SCFI")
    private String sc_Fi;
    @Column(name = "SERIE")
    private String serie;
    @Column(name = "SPEC")
    private String spec;
    @Column(name = "SPORT")
    private String sport;
    @Column(name = "THRIL")
    private String thril;
    @Column(name = "WEST")
    private String west;
    @Column(name = "NOTE")
    private String note;
    @Column(name = "Nombre_De_Voteurs")
    private String nombre_De_Voteurs;
    @Column(name = "DUREE")
    private String duree;
    @Column(name = "PRODUCTEUR")
    private String producteur;
    @Column(name = "En_Vedette")
    private String en_Vedette;
    @Column(name = "Audio_Francais")
    private String audio_Francais;
    @Column(name = "Audio_Anglais")
    private String audio_Anglais;
    @Column(name = "TRAITE")
    private String traite;
    @Column(name = "En_DOUBLE")
    private String en_Double;
    @Column(name = "Dernier_Episode_Visionne")
    private String dernier_episode_Visionne;
    @Column(name = "En_3D")
    private String en_3D;
    @Column(name = "Annee_Saison")
    private String annee_Saison;
    @Column(name = "Derniere_saison")
    private String derniere_Saison;
    @Column(name = "Produit_Creee_par")
    private String produit_Creee_Par;
    @Column(name = "AdresseResume")
    private String adresseResume;
    @Column(name = "NOUVEAU")
    private String nouveau;
    @Column(name = "J")
    private String J;
    @Column(name = "K")
    private String K;
    @Column(name = "L")
    private String L;
    @Column(name = "M")
    private String M;
    @Column(name = "N")
    private String N;
    @Column(name = "O")
    private String O;
    @Column(name = "P")
    private String P;
    @Column(name = "Q")
    private String Q;
    @Column(name = "R")
    private String R;
    @Column(name = "S")
    private String S;
    @Column(name = "T")
    private String T;
    @Column(name = "U")
    private String U;
    @Column(name = "V")
    private String V;
    @Column(name = "W")
    private String W;
    @Column(name = "X")
    private String X;
    @Column(name = "SOURCE")
    private String source;
    @Column(name = "Y")
    private String Y;
    @Column(name = "Film_Etranger")
    private String film_etranger;
    @Column(name = "Mini_Serie")
    private String mini_Serie;
    @Column(name = "Z")
    private String Z;
    @Column(name = "A")
    private String A;
    @Column(name = "B")
    private String B;
    @Column(name = "CATASTROPHE")
    private String catastrophe;
    @Column(name = "Version_Originale")
    private String version_Originale;
    @Column(name = "C")
    private String C;
    @Column(name = "BESTIOLE")
    private String bestiole;
    @Column(name = "TOUS")
    private String tous;
    @Column(name = "VUE")
    private String vue;
    @Column(name = "Pas_Vue")
    private String pas_Vue;
    @Column(name = "Adresse_Series")
    private String adresse_Series;
    @Column(name = "Coup_de_Coeur")
    private String coup_De_Coeur;
    @Column(name = "Serie_En_Cours")
    private String serie_En_Cours;
    @Column(name = "Serie_Complete")
    private String serie_Complete;
    @Column(name = "ESPION")
    private String espion;
    @Column(name = "ANTIQUE")
    private String antique;
    @Column(name = "POLITIQUE")
    private String politique;
    @Column(name = "PROCES")
    private String proces;
    @Column(name = "Super_Heros")
    private String super_Heros;
    @Column(name = "Tueur_en_Serie")
    private String tueur_En_Serie;
    @Column(name = "VAMPIRE")
    private String vampire;
    @Column(name = "ZOMBIE")
    private String zombie;
    @Column(name = "TERRORISTE")
    private String terroriste;
    @Column(name = "SORCELLERIE")
    private String sorcellerie;
    @Column(name = "ASIATIQUE")
    private String asiatique;
    @Column(name = "EROTIQUE")
    private String erotique;
    @Column(name = "NOUVEAUTE")
    private String nouveaute;
    @Column(name = "D")
    private String D;
    @Column(name = "SCIENTIFIQUE")
    private String scientifique;
    @Column(name = "ARCHEOLOGIE")
    private String archeologie;
    @Column(name = "Mon_Vote")
    private String mon_Vote;
    @Column(name = "Commentaire_Jules")
    private String commentaire_Jules;
    @Column(name = "SOCIETE")
    private String societe;
    @Column(name = "RELIGION")
    private String religion;
    @Column(name = "FORMAT")
    private String format;
    @Column(name = "Commentaire_Gerald")
    private String commentaire_Gerald;
    @Column(name = "qtp")
    private String qtp;
    @Column(name = "E")
    private String E;
    @Column(name = "Nouv_Com_Jules")
    private String nouv_Com_Jules;
    @Column(name = "Nouv_Com_Gerald")
    private String nouv_Com_Gerald;
    @Column(name = "EXTRATERRESTRE")
    private String extraterrestre;
    @Column(name = "Selection_Du_Jour")
    private String selection_Du_Jour;
}
